CCPSRCS += /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/GPX_Parser/GPX_Parser.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/MapConv/MapConv.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/MapConv/TileSystem/TileSystem.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/lv_ext/lv_obj_ext_func.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/lv_ext/lv_label_anim_effect.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/Stream/Print.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/Stream/Stream.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/PageManager/PM_Base.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/PageManager/PM_Anim.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/PageManager/PM_State.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/PageManager/PM_Drag.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/PageManager/ResourceManager.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/PageManager/PM_Router.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/TileConv/TileConv.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/TrackFilter/TrackPointFilter.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/TrackFilter/TrackLineFilter.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/PointContainer/PointContainer.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/lv_poly_line/lv_poly_line.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/TonePlayer/TonePlayer.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/WString/WString.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/DataCenter/Account.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/DataCenter/DataCenter.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/GPX/GPX.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/Time/Time.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/Time/DateStrings.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/StorageService/StorageService.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/SystemInfos/SystemInfosView.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/SystemInfos/SystemInfosModel.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/SystemInfos/SystemInfos.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/StartUp/StartUpView.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/StartUp/StartUp.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/StartUp/StartUpModel.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/StatusBar/StatusBar.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/Dialplate/DialplateModel.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/Dialplate/Dialplate.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/Dialplate/DialplateView.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/_Template/Template.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/_Template/TemplateModel.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/_Template/TemplateView.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/LiveMap/LiveMapView.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/LiveMap/LiveMapModel.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/LiveMap/LiveMap.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Pages/AppFactory.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/App.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/ResourcePool.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_Audio.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_SD_CARD.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_Encoder.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_Power.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_MAG.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_Clock.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_Buzz.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_GPS.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL_IMU.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/HAL/HAL.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DataProc.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_Recorder.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_Clock.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_SportStatus.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_Storage.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_MusicPlayer.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_TzConv.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_Power.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_SysConfig.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_TrackFilter.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_MAG.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_GPS.cpp \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Common/DataProc/DP_IMU.cpp 
        # /media/george/android/X-TRACK_D1s/x_track/USER/lv_port/lv_port.cpp \
        # /media/george/android/X-TRACK_D1s/x_track/USER/lv_port/lv_port_disp.cpp \
        # /media/george/android/X-TRACK_D1s/x_track/USER/lv_port/lv_port_fs_sdfat.cpp \
        # /media/george/android/X-TRACK_D1s/x_track/USER/lv_port/lv_port_indev.cpp 

CSRCS +=/media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/MapConv/GPS_Transform/GPS_Transform.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/lv_ext/lv_anim_timeline_wrapper.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/WString/dtostrf.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Utils/DataCenter/PingPongBuffer/PingPongBuffer.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_origin_point.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_bicycle.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_pause.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_start.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_storage.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_gyroscope.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_sd_card.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_locate.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_map_location.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_gps_pin.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_gps_arrow_default.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_gps_arrow_dark.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_gps_arrow_light.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_trip.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_compass.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_system_info.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_time_info.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_battery.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_stop.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_battery_info.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_menu.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_alarm.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Image/img_src_satellite.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Font/font_bahnschrift_65.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Font/font_agencyb_36.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Font/font_bahnschrift_32.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Font/font_bahnschrift_17.c \
        /media/george/android/X-TRACK_D1s/x_track/USER/App/Resource/Font/font_bahnschrift_13.c 